Added fp solution
mrandell777/ru-study-ruby pull request #2
Opened 2022-02-02 08:01 UTC by mrandell777

feature/fp

2022-02-04 13:08 UTC, moklidia requested changes

2022-02-04 13:08 UTC, moklidia commented on test/exercise/fp/solution.rb
> +          end
Давай попробуем разделить операции по типу: фильтрация, преобразование и аггрегация и неделать это все разом редьюсом

2022-02-04 13:08 UTC, moklidia commented on test/exercise/fp/solution.rb
> +            acc += 1
То же самое, что и выше

2022-02-04 13:08 UTC, moklidia commented on test/exercise/fp/solution.rb
> +          acc
То же самое, и давай будем давать говорящие названия переменным, а не просто `array`

2022-08-25 18:51 UTC, NickelGit requested changes

2022-08-25 18:51 UTC, NickelGit commented on test/exercise/fp/solution.rb
> +             !film['country'].nil? && film['country'].to_s.split(',').count >= 2
Вынеси пжлст условия в отдельный булев метод с говорящим названием в который мы будем передавать film и получать true или false.

2022-08-25 18:51 UTC, NickelGit commented on test/exercise/fp/solution.rb
> +        end
давай сократим эти действия до `names_string.count('и')'. так мы сразу получим количество символов `и` в строке.

2022-09-28 06:15 UTC, YJorge commented on test/exercise/fp/solution.rb
> +      def filter(film)
если метод возвращает true/false, в название добавляемся `?`. В этом случае лучше будет название ` valid?` или что-то в этом духе

2022-09-28 16:57 UTC, NickelGit approved these changes

2022-09-28 19:38 UTC, merged